### ISSUE TITLE
Annotating Your (Critical) CSS

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#1026]
[https://css-tricks.com/annotating-critical-css/](https://css-tricks.com/annotating-critical-css/)

**Comment by stefanjudis** [comment]
Hmm... @radibit this manual step to include these `! critical` thingies feels not that optimal. I think there are already nicer solutions including/describing automated critical css solutions.

What do you think?

**Comment by radibit** [comment]
Yes, I agree with you. After I created the issue I had a look on the other similar resources listed on perf-tooling and I also wasn't sure about this one.
