### ISSUE TITLE
Guide to private WPT instance

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#1041]
https://www.peterhedenskog.com/blog/2015/07/private-wpt-instance/

Works perfectly. thx @soulgalore

**Comment by soulgalore** [comment]
Cool :) You should also add this: https://wikitech.wikimedia.org/wiki/WebPageTest
There's some extra info there.

**Comment by marcobiedermann** [comment]
@soulgalore Do you wanna submit a pull request or should we add the resource for you?

**Comment by soulgalore** [comment]
hey @marcobiedermann you can add it if you want.
