### ISSUE TITLE
Angular Performance: Tuning the Engine

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#1052]
https://www.youtube.com/watch?v=LoIuokh6NUI

**Comment by stefanjudis** [comment]
@radibit please lease don't forget to set milestones... si that I've got an overview for the newsletter. :)

**Comment by radibit** [comment]
@stefanjudis I did that, but on the pull requests part of the last release :)

**Comment by stefanjudis** [comment]
Ahh right... Sorry - my fault... 🐼
