### ISSUE TITLE
Include Infographics?

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#1053]
Hey folks,

i was asked if we want to include infographics on perf-tooling?

What do you think about this.
The mentioned graphic would be this one -> http://www.onblastblog.com/speed-wordpress/ ( scroll down a bit ).

I think these graphics are nice in general but usually they're not technical enough for my taste.
What do you think?

@marcobiedermann @radibit @marhigh

**Comment by marcobiedermann** [comment]
Nice infographic, but I do not think it is worth it to open up a new section for it.
Also in my opinion it is a bit overkill to create another section for just a very few infographics.
My suggestion is to add the article and add a tag `infographic` to it.

**Comment by radibit** [comment]
I also believe that most of the infographics are not giving enough technical value as I'd like to see, but overall they can be an enjoyable information resource.

> My suggestion is to add the article and add a tag infographic to it.

👍
