### ISSUE TITLE
Collaboration with perf.email

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#1073]
As discussed with @benschwarz we'll start collaborating with perf.email and calibre.

That for we gonna add a section on home which will be something like "In proud collaboration with perf.email and calibre".

This might also include signing up for perf.email ( dropping our newsletter box ) and adding the perf.email signup.

@benschwarz You're up for implementing this in a way you'd like it to be presented?

Additional tasks:
- [ ] write "final" newsletter to inform our subscribers about this change
- [ ] figuring out a nice workflow to add perf.email content to perf-tooling

**Comment by benschwarz** [comment]
@stefanjudis This all sounds really good to me. 

I use a trello board for each new issue of perf.email, I can either share you in on that, or I can make it a part of my process to create github issues for everything that I ship in a perf.email? 

@stefanjudis What changes would you like me to make? What do I need to give you?

**Comment by stefanjudis** [comment]
@benschwarz cool! 🎉 

> I use a trello board for each new issue of perf.email, I can either share you in on that, or I can make it a part of my process to create github issues for everything that I ship in a perf.email?

Hmm not sure, for the start I'd prefer just a preview a few days ahead in my inbox, so that I can add stuff to perf-tooling. :) Would this work for you?

Don't think it's needed for you to create issues all the time. :)

Only thing we'd need from you would be a PR that replaces our signup form with yours. And maybe something like "in collaboration with calibre" and a bit of intro.

When this is done - I'll write the final newsletter to inform our subscriber about perf.email.

And I think this is it. :)
