### ISSUE TITLE
How loading JavaScript can slow websites down

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#1141]
[How loading JavaScript can slow websites down ](https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2016/september/how-loading-javascript-can-slow-websites-down/)

**Comment by stefanjudis** [comment]
I didn't like that one too much tbh.

**Comment by radibit** [comment]
ok, I had some doubts, too. Closing the issue.
