### ISSUE TITLE
Perceived Performance

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#1153]
[http://assets.eli.wtf/talks/perceived-perf-talk/#/28](http://assets.eli.wtf/talks/perceived-perf-talk/#/28)

**Comment by stefanjudis** [comment]
Not sure about that... I think it probably is a strong talk, but slides only doesn't work that well for me.

**Comment by radibit** [comment]
Yep, I agree with you. I guess it'd a nice addition to the website if we can find the actual talk :)
Closing the issue.
