### ISSUE TITLE
Perceived performance increase for images by providing a gradient fallback

### ISSUE THREAD

**Issue by ben-eb** [stefanjudis/perf-tooling#1156]
Would you be amenable to listing https://github.com/ben-eb/postcss-resemble-image as a tool and http://csswizardry.com/2016/10/improving-perceived-performance-with-multiple-background-images/ as an article? I think this small trick makes a website appear to load faster; what do you think? 😄

**Comment by marcobiedermann** [comment]
@ben-eb Thank you Ben for your suggestions. Great resources. Would you like to submit them by yourself or should we add them for you?

**Comment by ben-eb** [comment]
Sure, I don't mind. One question though, how do you get the article length?

**Comment by marcobiedermann** [comment]
@ben-eb Great! 🎉 

I usually copy the article into Pages. It shows the number of words in the text at the bottom 😄
