### ISSUE TITLE
Reorganizing Website Architecture for HTTP/2 and Beyond

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#1161]
http://www.slideshare.net/kazuho/reorganizing-website-architecture-for-http2-and-beyond

**Comment by radibit** [comment]
Will add this later today 👍

**Comment by radibit** [comment]
Seems it has been already added with the following [commit](https://github.com/stefanjudis/perf-tooling/pull/1162/commits/e001b10640cf161aa7d6f3e15a385ee74f655be0).
