### ISSUE TITLE
add Ben to collaborators on index

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#1169]
Heyo,

I met @ben-eb at a conference. And we both thought that it would be nice to get him on board...

That for here's the quick check if everybody is fine with that and of course we have to add him to the index page then. :)

@marhigh @marcobiedermann @radibit

**Comment by marcobiedermann** [comment]
Alsolutely, welcome Ben :)

**Comment by stefanjudis** [comment]
Whooop whoooop!

**Comment by ben-eb** [comment]
Sweet! Thanks. 🎉

**Comment by stefanjudis** [comment]
We could also bring the newsletter back to life, if you feel like it. (no pressure). :)

**Comment by ben-eb** [comment]
I like the idea of collaborating with [perf.email](https://perf.email), is this something we're still planning to do? https://github.com/stefanjudis/perf-tooling/issues/1073

**Comment by stefanjudis** [comment]
It's still waiting for the PR by @benschwarz to add the newsletter sign up box. ;)

I was up for the collaboration because perf.email has more traction and I was running short on time. So I'm just asking if you'd be up for newslettering. 😄

**Comment by ben-eb** [comment]
What's involved? 😄

**Comment by stefanjudis** [comment]
Switched to gitter...
