### ISSUE TITLE
Update gependencies with Greenkeeper

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#1183]
I am currently updating all dependencies one by one and check each if the site is still running.
After this process is finished, I suggest setting up [Greenkeeper](https://greenkeeper.io/) which will open up a pull request if any dependency got updated.

**Comment by stefanjudis** [comment]
> I suggest setting up Greenkeeper which will open up a pull request if any dependency got updated.

I tried Greenkeeper and the idea is great. But overall it brings a lot of noise. We only have bare test coverage which would mean to check the gazillion PR's created by hand.

For me Greenkeeper only makes sense in combination with high test coverage and probably semantic-release.

cc.
@ben-eb @radibit

**Comment by radibit** [comment]
Yes, I'm sharing @stefanjudis opinion on this - nice idea, but probably not entirely suitable with the current perf-tooling release workflow.

**Comment by ben-eb** [comment]
Yeah, you'll probably want more automated tests to see any value. I think because it's a website and not a module, we can get away with infrequent, periodic updates.

**Comment by stefanjudis** [comment]
@marcobiedermann Sorry, but I'm closing this one then. Voting is rather clear. :)

**Comment by marcobiedermann** [comment]
Sure :)
