### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#1200]
I've started using emojis in my last few project and used them also in the latest commits on this project. I use [gitmoji](https://gitmoji.carloscuesta.me/) as reference.
What do you guys think about including them?
I think they give a nice little indicator at the first look.
If you are fine with this addition, I suggest including a short description in `CONTRIBUTING.md`.

**Comment by stefanjudis** [comment]
I have no opinion on that one. ¯\_(ツ)_/¯

cc. @ben-eb @radibit

**Comment by radibit** [comment]
I'm fine with the gitmoji approach :) Already using it in two other projects.
However it seems a bit odd to me if the commit message contains different actions e.g. `⬆ 🐛 update package x and fix bug y`, but it might be just me.

**Comment by radibit** [comment]
So if we follow the gitmoji approach, we can indicate that with an appropriate badge:

<img src="https://img.shields.io/badge/gitmoji-%20%E2%9A%A1%20%F0%9F%98%8D-40C4FF.svg">

Any objections, is it too much or I can update that quickly on the readme? :)

**Comment by stefanjudis** [comment]
We have also to decide which one to take for content editions...

I went with 📝?

👍 for the badge.

**Comment by radibit** [comment]
Maybe in the context of perf tooling, adding more articles, tools etc. can be considered as a feature ✨ , but yeah for me the 📝  is absolutely fine.

**Comment by ben-eb** [comment]
Sure, why not.

> However it seems a bit odd to me if the commit message contains different actions e.g. `⬆ 🐛 update package x and fix bug y`, but it might be just me.

Good argument for practicing atomic commits. 😄

**Comment by radibit** [comment]
Closing it as it was solved with #1242.
