### ISSUE TITLE
Translating Less to PostCSS

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#1203]
Hey guys, we are currently using LESS preprocessor for our CSS.
I would like to drop LESS and translate everything to pure CSS.
At this time, CSS does support variables (custom properties) and this way we are save to maintain our code in the future. Also Chrome Canary does support them natively.

I would also like to introduce PostCSS because most CSS modules use them under the hood nowadays (e.g. Autoprefixer).

Any thought on this topic?

**Comment by ben-eb** [comment]
Sure, sounds good to me. 👍
