### ISSUE TITLE
Compressive Images

### ISSUE THREAD

**Issue by ben-eb** [stefanjudis/perf-tooling#1246]
https://www.filamentgroup.com/lab/compressive-images.html

**Comment by stefanjudis** [comment]
Hmm not sure about that one...

I'd always go for a real responsive image solution before using a technique like this... :)

**Comment by radibit** [comment]
Same thought from my side. I'd rather use `srcset` + [picturefill polyfill](http://scottjehl.github.io/picturefill/).

**Comment by ben-eb** [comment]
OK, fair enough. I'll close this one. 👍
