### ISSUE TITLE
Performant lazy loading library

### ISSUE THREAD

**Issue by ApoorvSaxena** [stefanjudis/perf-tooling#1283]
Performant lazy loading library using InteractionObserver
https://github.com/ApoorvSaxena/lozad.js

**Comment by stefanjudis** [comment]
If you hand in a PR I'm happy to take it. ;)

Can't promise when I'll be able to add it. :)

**Comment by ApoorvSaxena** [comment]
sure, will send in a PR soon :)

**Comment by ApoorvSaxena** [comment]
@stefanjudis here's the PR as asked https://github.com/stefanjudis/perf-tooling/pull/1286

**Comment by stefanjudis** [comment]
👍
