### ISSUE TITLE
Chen Shay: You don't need AMP for that | JSConf EU 2017

### ISSUE THREAD

**Issue by sareg0** [stefanjudis/perf-tooling#1322]
Type: Video Proposal
Title: Chen Shay: You don't need AMP for that | JSConf EU 2017
Link: https://youtu.be/EcG5ll_6fJk
Duration: 23m38s

**Comment by stefanjudis** [comment]
Thanks. @sareg0.

I'll watch it later. :)

**Comment by stefanjudis** [comment]
Jup! 👍🏻 Thanks for bringing this one up I'll add it in a few min. 🎉
