### ISSUE TITLE
What we talk about when we talk about web performance – Patty Toland – btconfDUS2017

### ISSUE THREAD

**Issue by sareg0** [stefanjudis/perf-tooling#1323]
Type: Video Proposal
Title: What we talk about when we talk about web performance – Patty Toland – btconfDUS2017
Link: https://youtu.be/3RFlDdMIVYY
Duration: 47m02s

Note: This talk is already up from a Smashing Conf edition (http://www.perf-tooling.today/videos?q=patty). Not sure if you want to replace it, or have both, since there could be some new stuff.

**Comment by stefanjudis** [comment]
Woohoooo! 👋 
I'd rather prefer to update the existing one. :) 

Wanna hand in a quick PR? 😊

**Comment by sareg0** [comment]
Will do
