### ISSUE TITLE
Events Section?

### ISSUE THREAD

**Issue by sareg0** [stefanjudis/perf-tooling#1324]
Perhaps it could be nice to have a list of upcoming and past webperf events e.g. DeltaV Conf, https://certifiedfreshevents.com/events/improving-your-apps/, #perfmatters conf https://t.co/xWls64NYAu

🤔

**Comment by radibit** [comment]
I think it's a nice idea 🙂  

However, it goes a little bit off the context of curating web performance tools and resources. Maybe if it's somehow combined with the `Videos` section, where we can display the most interesting talks for each event (though not every conference is providing recorded versions of the talks)?

**Comment by radibit** [comment]
I think it's a nice idea 🙂  

However, it goes a little bit off the context of curating web performance tools and resources. Maybe if it's somehow combined with the `Videos` section, where we can display the most interesting talks for each event (though not every conference is providing recorded versions of the talks)?

**Comment by sareg0** [comment]
Right-o. Perhaps not the right Idea for this type of resource collection then. I'll close it up, and stew on what you mention: "somehow combined with the Videos section, where we can display the most interesting talks for each event"

Thanks for the consideration!
