### ISSUE TITLE
Add sloth

### ISSUE THREAD

**Issue by denar90** [stefanjudis/perf-tooling#1350]
Hi guys,

I've built chrome extension for throttling page loading speed - https://github.com/denar90/sloth
It was born after [tweeter discussion](https://twitter.com/denar90_/status/964612738235469825).

Would you be interested in adding this one?

**Comment by stefanjudis** [comment]
Yeah. :)  Looks nice.

May I ask how did you come up with these default conditions?

**Comment by denar90** [comment]
Do you mean downgrading network speed?

**Comment by stefanjudis** [comment]
I mean these:

>    CPU: 2x throttling
>    Network connection: 1.6Mbps - download, 750Kbps - upload

I was expecting several options. :)

**Comment by denar90** [comment]
They are [hardcoded](https://github.com/denar90/sloth/blob/master/extension/popup.js#L3-L20) for now, but I have an [issue](https://github.com/denar90/sloth/issues/1) to make it configurable

**Comment by stefanjudis** [comment]
Okay. got it. :) But good stuff. :) 👍🏻 thx!
