### ISSUE TITLE
Video Proposal: Web performance webinar (DeltaV Conf)

### ISSUE THREAD

**Issue by sareg0** [stefanjudis/perf-tooling#1356]
**Title:** Web performance webinar (12 April 2018) - DeltaV Conf
**Duration:** 45:20
**Description:** "Web performance experts Léonie Watson, Harry Roberts, Laura Sheridan, and Tobias Baldauf joined us to share their insights on optimising the web and what they're looking forward to at the first DeltaV Conf in May 2018."
**Link:** https://youtu.be/VamKs0HKvQA

**Comment by stefanjudis** [comment]
Wooohooo! :) Haven't watched it yet, but looking at the participants I'm sure it was great. 

Could you provide a PR @sareg0? That would be fantastic. 👌

**Comment by sareg0** [comment]
Yes, I can do one later today for it.
