### ISSUE TITLE
Implement property to show if it's paid or not

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#18]

**Comment by marcobiedermann** [comment]
@stefanjudis How about this topic? I would go with the tooltip solution

**Comment by stefanjudis** [comment]
@marcobiedermann 

Hmm, actually I'd prefer some watermark next to the title or something.

Putting it next to platform no matter if tooltip or own icon, doesn't feel correct to me. 
It should also be visible without user interaction.

What do you think?

**Comment by marcobiedermann** [comment]
What do you think works better?

```
"name" : "New Relic",
"service" : {
  "url" : "http://newrelic.com/",
  "isPaid" : true
},
```

or

```
"name" : "New Relic",
"service" : "http://newrelic.com/",
"isPaid" : true,
```

I think the first one works better because we can set it individually to the platform.

**Comment by stefanjudis** [comment]
yeps - first one for sure. :)

**Comment by marcobiedermann** [comment]
Alright, I will tackle this one soon :)

**Comment by lovell** [comment]
In terms of UI, paid vs non-paid feels like a filtering thing, be it an explicit form option or an implicit but visible symbol. Having to access per-tool tooltips requires too much effort on behalf of the visitor.

I notice you're using Google Analytics. If you're not already, perhaps add event tracking on:

* what words/phrases a visitor types in the search box
* which outgoing links they follow
* how long they spend on a page before finding a paid (or non-paid) tool of interest (= last outgoing link?)

Include the paid vs non-paid attribute in any event and you might be able to cluster these events, e.g. visitors who only clicked on free, open source tools.

Good luck!

**Comment by stefanjudis** [comment]
@lovell 

> Having to access per-tool tooltips requires too much effort on behalf of the visitor

Totally agree on that.

The extended analytics tracking is a good idea - we're planing on filters anyway.

Thanks for ideas and feedback. :)
