### ISSUE TITLE
The Ultimate Checklist for Optimizing Web Performance

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#260]
http://www.yottaa.com/blog/bid/296075/Infographic-The-Ultimate-Checklist-for-Optimizing-Web-Performance

**Comment by marcobiedermann** [comment]
https://twitter.com/m412c0b/status/593391035742552064

**Comment by stefanjudis** [comment]
:+1:

**Comment by ben-eb** [comment]
Dead link, so I'm going to close this. 😄
