### ISSUE TITLE
What about this books section thing?

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#275]
@marcobiedermann Not sure about this.

**Comment by stefanjudis** [comment]
![screenshot 2015-01-28 23 52 43](https://cloud.githubusercontent.com/assets/962099/5948858/cbb25cd6-a748-11e4-9a5c-78d9b6ed929b.png)


you turn. :)

**Comment by marcobiedermann** [comment]
Yeah, as I mentioned, is there a way to crop the images via node? Or would you crop it yourself and add the images to the repo?

**Comment by stefanjudis** [comment]
sure we can crop images - but I'd check in the images in the git repo. Because there is no central api to ping. 

So my idea would simply be, to add images, crop them as needed and then serve them from our cdn ( fastly ). :)

**Comment by stefanjudis** [comment]
@marcobiedermann any chance we can tackle this one soon? :)
