### ISSUE TITLE
open slides/videos in modal

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#334]
Embed videos and display them in a full-screen modal / popup to decrease bounce rate and get longer stay-time per page

**Comment by stefanjudis** [comment]
Let's do it... I'll do the same for slides. :)

**Comment by marcobiedermann** [comment]
Yey, perfect!

**Comment by stefanjudis** [comment]
@marcobiedermann need the slides to be done first though.

Some css adjustments are needed over there. :)

**Comment by stefanjudis** [comment]
@marcobiedermann 

First version is pushed... Really basic but working.

```
      <div id="modal">
        <div id="modalContent"></div>
      </div>
```

`modalContent` is filled with content. and this is happening here in `modal.js`:

```
    if ( filteredList.length && filteredList[ 0 ].html ) {
      event.preventDefault();

      elements.modalContent.innerHTML = filteredList[ 0 ].html;
    }
```

**Comment by stefanjudis** [comment]
@marcobiedermann 

Please think of tagging your commits with issue number.

**Comment by marcobiedermann** [comment]
Ups, sorry. Forgot to include issue number.

Styling of modal is done form my end. Two things have to be done:
- [ ] modify template: wrap div around content
- [ ] close button is not working: I do not know why. Works with text, does not with svg close icon. Any idea?

**Comment by stefanjudis** [comment]
> close button is not working: I do not know why. Works with text, does not with svg close icon. Any idea?

Fixed but not yet pushed

> modify template: wrap div around content

Don't get it? Should I do this? Or is there anything you need? :)

Also the iframes were responive when I handed them over to you, now they are not anymore. :(

![screenshot 2015-04-12 22 49 40](https://cloud.githubusercontent.com/assets/962099/7107467/8ed88eae-e166-11e4-9d2d-e2654e1a44e6.png)

![screenshot 2015-04-12 22 48 44](https://cloud.githubusercontent.com/assets/962099/7107469/95592df6-e166-11e4-86bf-0962451b2bdc.png)

**Comment by stefanjudis** [comment]
@marcobiedermann 

I added a "open in new tab" link. Is this fine for you? Or wanna prettify it?

![screenshot 2015-04-18 19 23 23](https://cloud.githubusercontent.com/assets/962099/7216441/99ab4b0c-e600-11e4-9ca3-f4b73f16b571.png)
![screenshot 2015-04-18 19 23 31](https://cloud.githubusercontent.com/assets/962099/7216442/99b0dc66-e600-11e4-85c6-d803d6c7c290.png)


I'd love to have feedback of this implementation by you guys.

@marcobiedermann @radibit @marhigh
