### ISSUE TITLE
wp-tevko-responsive-images

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#386]
https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images

@marcobiedermann 

what about listing tools for common cms systems like wordpress, drupal or typo3.
We would need to add more circles or?

What do you think. :)

**Comment by marcobiedermann** [comment]
I agree. I found a nice WP icon on [iconmonstr](http://iconmonstr.com/wordpress-4-icon/)  from which we get all our other icons. I also tweeted the author if he could add some more. Hope for the best :)

**Comment by stefanjudis** [comment]
Great - do you mind if I assign this one to you then. 

And you'll add it whenever the icon is there and all is set up? :bowtie:

**Comment by marcobiedermann** [comment]
Sure, go for it
