### ISSUE TITLE
Implement enhancejs and cookie logic on server side to not always serve inline css and all svg icons

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#400]

**Comment by radibit** [comment]
@stefanjudis 

Is this the right way of obtaining the path to the ``` main.css ``` file ``` <%= cdn %>/main.css ```?

I'm asking, because if I understand correctly the enhancejs approach requires first to provide the URL to the CSS file in order to be loaded async, cached and set a coockie to refer to it for a later use?

So the ``` head ``` configuration should be similar to the fowling:

``` html
<!doctype html>
<html>
<head>
	...
	<meta name="maincss"  content="<%= cdn %>/main.css">
<!--#if expr="$HTTP_COOKIE=/maincss\=true/" -->
	<link rel="stylesheet" href="<%= cdn %>/main.css">
<!--#else -->
	<style>
		/* critical CSS styles for this template go here... */
	</style>
<!--#endif -->	
	<script>
		<!--#include virtual="<%= cdn %>/tooling.js" -->
	</script>
	<noscript><link rel="stylesheet" href="<%= cdn %>/main.css"></noscript>
	...
</head>
```

Thanks!

**Comment by stefanjudis** [comment]
@radibit 

Jap, pretty much. `cdn` provides the correct path in production environment and is falling back to `/` in dev env's.

Only md5 hashed query param ( or file name ) is missing in your example. :)

**Comment by stefanjudis** [comment]
@radibit good luck buddy. :P

**Comment by radibit** [comment]
Hey @stefanjudis 

It seems there is a problem on my side running `gulp dev` or any other gulp tasks.
Each time I'm receiving the following error message:

```console
Error: Cannot find module 'defaults'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/rbit/Projects/perf-tooling/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs/lib/src/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Already tried several times cleaning / re-installing all npm modules. Any ideas will be welcome :-)

**Comment by stefanjudis** [comment]
is this also happening in `master`?

**Comment by radibit** [comment]
Yes, same error on `master`.

One more question - can you please share what was your idea of using the [enhancejs](https://github.com/filamentgroup/enhance) approach for the svg icons. More specifically how the icons should be loaded if the cookie indicator is true meaning that the page was already rendered once e.g.

```html
<!--#if expr="$HTTP_COOKIE=/svgicons\!== true/" -->
<div class="svgIcons"><%= svg %></div>
<!--#else -->
// Need a way of referencing the svg icons using the relative path
<!--#endif -->
```

Thank you!

**Comment by stefanjudis** [comment]
Which node version are you on?
Let's discuss tomorrow. :)

**Comment by stefanjudis** [comment]
Whooop whooop.
