### ISSUE TITLE
Implement debug param to check data in memory

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#405]
I'm thinking of something like ```?fancy_debug=true``` which will return the data, that is stored in memory at given time.

**Comment by marcobiedermann** [comment]
:+1: I like the idea!

**Comment by stefanjudis** [comment]
![screenshot 2015-04-09 23 32 18](https://cloud.githubusercontent.com/assets/962099/7077399/cd2b8740-df10-11e4-922c-3f986eb44520.png)

**Comment by stefanjudis** [comment]
It's listing `people` and the depending `list` if on a list page.

Just append `?debug=true` to make it work.
