### ISSUE TITLE
Multiplexing with SPDY and HTTP/2

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#440]
https://www.youtube.com/watch?v=J_BxVEOVRNw&utm_source=webopsweekly&utm_medium=email

@marcobiedermann 

can you check this one - I really liked the demo time. But for some reason I'm not sure.

**Comment by marcobiedermann** [comment]
Hmm… hard decision. Nice talk, really informative.  Yeah, he talked about HTTP2 and SPDY and how it might look in the near future but I  give it a :-1: for our project because I think this is more network logic related than performance tools.

**Comment by stefanjudis** [comment]
> for our project because I think this is more network logic related than performance tools.

I think we're already far away from performance tools only, which is a good thing in my mind.
A pitty with the domain though: :P

We're already covering:

- tooling
- culture
- future trends
- motivation
- network stuff

So we might adjust the mindset a bit to *Educational materials dealing with web performance topics* :D

**Comment by marcobiedermann** [comment]
@stefanjudis Thats a point. I have to agree this that statement. The problem I have is that I think we are getting too many resources and for someone new to our site might me confused or might have too many topics to look into. So that is why I try to keep them more relevant to performance tools / tricks / tipps.
Maybe when we add the sorting / filter option and the new timeline you mentioned there will be a better path / guide for the resources.

So to come to a conclusion: We add this video, don't we?
@marhigh, @radibit What are you opinions on the general performance tooling topic?

**Comment by stefanjudis** [comment]
Yeah for me the problem is more about making the content more accessible rather than not adding good stuff. 

I think when following stuff is added it might be great:

- filters
- proper sorting ( last stuff on top )
- level was also a topic
- maybe additionally to categories we could over something visually showing of education, tooling, ...

Once the filters are done, we should all make a brain storm session on the direction we wanna go. :)

@marhigh @radibit

**Comment by radibit** [comment]
Definitely the filter / sorting mechanism will provide a quick and easy way to navigate through all available resources especially with the increase of their number. 

> Once the filters are done, we should all make a brain storm session on the direction we wanna go. :)

:+1: 

I think the meaning of the term `performance` can be applied to many aspects of the web development like better workflow, team culture and motivation, best practices, toolset etc. In my opinion `tooling` can be described as the way to achieve better results in these mentioned areas :-)

In the context of this thoughts I think the talk is very interesting and can be added to the resources, but I have to agree with @marcobiedermann about the part of adding different types of resources giving in the same time broader view of the project's meaning without proper way to apply filters, sorting etc.
