### ISSUE TITLE
comcast

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#441]
https://github.com/tylertreat/Comcast?utm_source=webopsweekly&utm_medium=email

**Comment by marcobiedermann** [comment]
@stefanjudis What do you think. Only add it to CLI platform or add it three times for Windows, Mac and Linux? I would keep it just to CLI

**Comment by stefanjudis** [comment]
@marcobiedermann yeah only CLI is fine, I guess.

Thought of windows, mac, linux as standalone apps.
