### ISSUE TITLE
Benchpress

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#442]
https://github.com/angular/benchpress

@marcobiedermann 

this is mostly angular specific. I might make sense to add an angular logo? WDYT?

**Comment by marcobiedermann** [comment]
![perf-tooling-benchpress](https://cloud.githubusercontent.com/assets/5244986/6204472/26769602-b54d-11e4-9837-844d34ecbe21.png)

**Comment by stefanjudis** [comment]
@marcobiedermann 

:heart: it!
