### ISSUE TITLE
I am the fold

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#446]
http://www.iamthefold.com/

Really interesting study, but I am not sure whether to include it or not.

**Comment by marcobiedermann** [comment]
I really like it but I would wait until the author writes a whole article about this.
> Full write up coming soon on my personal site, [iest.co](http://iest.co./).

**Comment by stefanjudis** [comment]
@marcobiedermann 

Yeah it's nice - but not really related. So let's close here.

But as usual - I you wanna discuss, let's do it. :)
