### ISSUE TITLE
Add CDNs

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#460]
@stefanjudis How about adding some CDNs?

**Comment by stefanjudis** [comment]
hmm - not sure.

this is then kind of a commercial thing, or?
And I don't know any free cdn.

**Comment by marcobiedermann** [comment]
That's a point.
I am also not that sure. I thought about it because awesome-wpo is listing some CDNs.

**Comment by stefanjudis** [comment]
yeah - but... well not convinced to be honest...

I'll close it? And if you want to discuss further let's reopen. :)
