### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by cutalion** [stefanjudis/perf-tooling#472]
http://webpack.github.io/

> webpack takes modules with dependencies and generates static assets representing those modules.

**Comment by stefanjudis** [comment]
@cutalion 

I'm not sure about webpack, it's more a module loader isn't it?

**Comment by marcobiedermann** [comment]
:-1: @cutalion Thank you for the suggestion but I think this is not a web performance tool in particular.

**Comment by cutalion** [comment]
Yes, it is not a web performance tool. But it resolves dependencies between
modules in large web applications and splits modules into parts. Of course
it can minify scripts and styles, inline images into CSS, etc. But more
important that it can help optimize number of requests AND size of
downloaded assets at the same time.

**Comment by stefanjudis** [comment]
Hmm not really convinced tbh.

Then we should include require.js ( with r.js), system.js, browserify and all the other module loaders also.
And this is kind of missing the point maybe?

**Comment by cutalion** [comment]
The reason of using webpack is not module loading. Not only that.
It's actually alternative to require.js or browserify.

But it can do more for optimization - split code into bundles for each page
to load assets required for particular page only. That minimizes first page
load by not downloading all scripts. It can then async load other bundles
when needed.  It also extracts shared code (between bundles) and only loads
it once. And it can pack images and CSS into bundles.


Sorry, maybe it's not so awesome to be added to perf-tooling. But it
definitely was built with optimization or for optimization in mind.

It's ok to just close this issue - I don't take part in webpack development
or something.
Np :)

**Comment by stefanjudis** [comment]
@cutalion 

Well it's awesome for sure - but as said I'd say its focus is more on module loading rather than perf optimization.

But thanks for mentioning it and if anything else comes to mind ping us. :)
