### ISSUE TITLE
mod pagespeed

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#487]
https://code.google.com/p/modpagespeed/
https://github.com/pagespeed/ngx_pagespeed

**Comment by stefanjudis** [comment]
@marcobiedermann wanna check for an `apache` and `nginx` logo?

**Comment by marcobiedermann** [comment]
Sure!

**Comment by stefanjudis** [comment]
@marcobiedermann ping. :)

**Comment by marcobiedermann** [comment]
there you are :)

**Comment by stefanjudis** [comment]
@marcobiedermann uuuuh nice!!!
