### ISSUE TITLE
PerfTests

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#494]
https://github.com/kogarashisan/PerfTests

**Comment by stefanjudis** [comment]
@marcobiedermann I don't get this one - this is a test suite for micro benchmarks?

**Comment by marcobiedermann** [comment]
> Accurate tests of JavaScript class inheritance models
To be honest I do not get the real purpose of this either. I've added this because I've seen this repo on Twitter or GitHub. Haven't looked deeper into it.
I've red the Readme but it does not look like a tool, more like a benchmark run. No that useful for a daily performance tip. I close it for now, but if anyone feels different, feel free to reopen this issue :-1:
