### ISSUE TITLE
The path to performance

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#499]
https://speakerdeck.com/katiekovalcin/the-path-to-performance

**Comment by marcobiedermann** [comment]
:-1: Too many quotes and stats instead of tipps and techniques in my opinion

**Comment by stefanjudis** [comment]
Don't agree on this one.

There are useful insights on how to build up a performance culture inside of the company - which is usually the hardest part, when dealing with designers and marketing folks.

For me it's a :+1: .

Maybe we can get another opinion in here? @radibit @marhigh

**Comment by marcobiedermann** [comment]
I have to agree with you, if you see it from that perspective

**Comment by radibit** [comment]
I think it's a good generalized overview of the performance aspects valid for the different perspectives in a company. 

Probably the good thing about this presentation is its wider target audience, not focused only to developers, more like a motivational resource.
