### ISSUE TITLE
strategies for staying on top of web performance

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#508]
https://css-tricks.com/strategies-for-staying-on-top-of-web-performance/

**Comment by marcobiedermann** [comment]
Damn it, you were just a few minutes faster :P

**Comment by stefanjudis** [comment]
@marcobiedermann 

Touché my friend. :P

**Comment by marcobiedermann** [comment]
@chriscoyier Do you wanna add this by your own? Would be an honour to see you as a [contributor](http://perf-tooling.today/#contributors) on our little performance project :)

**Comment by chriscoyier** [comment]
I love the site! Feel free to add my article. I could do it myself, but I feel like adding an anchor link to an html document is a pretty cheap way to be a real _contributor_, yeah know?

**Comment by marcobiedermann** [comment]
@chriscoyier Alright, however you like to. We would love to see your face on our page, but we can add your article as well :). If you got any more resources, feel free to add them to our project. Thanks.
