### ISSUE TITLE
Product Hunt entry

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#514]
@marcobiedermann @stefanjudis 

Hi guys,

What is your opinion for eventual entry to the [Product Hunt](http://www.producthunt.com/) platform? I think it will be a good option to introduce perf-tooling to more people and get more attention :-)

**Comment by stefanjudis** [comment]
I know the service vagely but am not sure, if perf-tooling is the correct thing.

But if you think it is - sure let's do? How do we do it?

Anything against that @marcobiedermann ?

**Comment by marcobiedermann** [comment]
I have to agree with @stefanjudis. I think perf-tooling might not be the right resource for this site.
@radibit If you like to try this anyway, go ahead. Let's see if it's gonna work.

**Comment by radibit** [comment]
OK, thanks for sharing your opinion.

**Comment by stefanjudis** [comment]
@radibit so you're giving it a shot?

As said - I don't really now product hunt - if there is similar stuff it might be worth a try. :)

**Comment by radibit** [comment]
@stefanjudis 
Yes, I will give it a shot as I think there are similar things submitted to their platform e.g. 
 * [anicollection.github.io](anicollection.github.io)
 * [startup-videos.com](startup-videos.com)
 * [libraries.io](libraries.io)
  etc. 

And these are examples from the last few days. 

I agree with @marcobiedermann that this is not absolutely the best fit for what perf-tooling represents, but nothing to loose by trying it :-)

**Comment by stefanjudis** [comment]
Cool. Then *rock on* and we can close this one for, now?

Would be great if you could post outcome in here. And we'll share impact on analytics if so. :)

**Comment by radibit** [comment]
It seems they added an invitation process in order to be able to submit a product, so I will create the entry as soon as I'm invited and will share the result after that :-)
