### ISSUE TITLE
Advertising

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#526]
> Hi there,
I'm Iulia and I work for ...
I'd like to explore the options for advertising some relevant deals on Performance Tooling Today with a sponsored post or dedicated newsletter.
Please send me the rates and the updated stats (monthly hits / newsletter subscribers etc).
Thanks,
Iulia

What do we think of that - I'm sceptical.

@radibit @marcobiedermann @marhigh

**Comment by marcobiedermann** [comment]
I would not include any ads in the newsletter. If we add ads to the site, I would put it beneath the filter / sorting sidebar.

**Comment by radibit** [comment]
@stefanjudis @marcobiedermann @marhigh 

It doesn't seem to me like a properly defined offer, mostly of the lack of actual details.

I'm not very proficient on the advertising aspect, but `sponsored post or dedicated newsletter` won't be the best fit at the moment in my opinion.

**Comment by marhigh** [comment]
I think it's worth asking what the deal is but am also skeptical of adding
ads at this point.

**Comment by stefanjudis** [comment]
I'll close this one - the plattform is not what I'd like to have as advertising.
