### ISSUE TITLE
add combine-media-queries task

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#540]
How about adding this to our gulp task. Saves some extra bytes.
https://www.npmjs.com/package/gulp-combine-media-queries/

**Comment by stefanjudis** [comment]
well yeah - if you wanna do this. sure. :)

**Comment by stefanjudis** [comment]
Outcome:

```
### before
main.css - 11K
main.css.gz - 3,1K

### include combine media queries
main.css - 11K
main.css.gz - 3,1K
```

well. :D yeah let's keep it.

**Comment by marcobiedermann** [comment]
@stefanjudis You are comparing the same file. It does make a difference. 286 bytes. Not that much but every byte counts :D
```
-rw-r--r--   1 marcobiedermann  staff   11422 Apr 10 00:00 main-new.css
-rw-r--r--   1 marcobiedermann  staff   11708 Apr 10 00:03 main-old.css
```

:+1: For gulp module :)

**Comment by stefanjudis** [comment]
Nope I didn't. I just disabled and enabled it.

Ja okay. This minor difference was not shown my my `ll`. Wanna past gzipped also?

**Comment by marcobiedermann** [comment]
Yeah, here are the results:
```
-rw-r--r--   1 marcobiedermann  staff    3158 Apr 10 00:00 main-new.css.gz
-rw-r--r--   1 marcobiedermann  staff    3178 Apr 10 00:03 main-old.css.gz
```

20 Bytes diff when gzip is enabled

**Comment by stefanjudis** [comment]
Haha nice!!!!

But yeah every byte counts. :D
