### ISSUE TITLE
Help with newsletter

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#554]
Hey @radibit, @marhigh, @marcobiedermann,

sorry for asking - but life's been too stressful over the last couple of weeks and I'd like to ask if someone can help with the latest newsletter send out.

After latest deploy yesterday ( oh well - we need to change stuff ) - I'd focus to fix the instable state we have atm.

Anyone time and passion to write a newsletter? No probs if not. :)

**Comment by radibit** [comment]
I can do it :-)

I will need more info on the resources that should be included in the upcoming newsletter and some clarifications regarding the steps of how to send / publish it.

**Comment by stefanjudis** [comment]
Included resources:

https://github.com/stefanjudis/perf-tooling/issues?q=milestone%3Av1.23.0
