### ISSUE TITLE
Better by proxy

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#557]
https://speakerdeck.com/tkadlec/better-by-proxy-at-mobilism-2015

**Comment by marcobiedermann** [comment]
Not bad slides but we just covered this a thousand times: Minify and concat resources -> fewer bytes -> less bandwidth and roundtrips -> faster websites. :-1: from my point.

**Comment by stefanjudis** [comment]
> minify and concat resources -> fewer bytes -> less bandwidth and roundtrips

don't think that this was the core of the slides, but agree kind of.

I think proxy browsers are super interesting, but might not be the right place here.
