### ISSUE TITLE
http://sizersoze.org/

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#562]
http://sizersoze.org/

**Comment by marcobiedermann** [comment]
Has anyone tested this site? I've tried it three times on different days and it dos not work for me.

**Comment by stefanjudis** [comment]
https://twitter.com/stefanjudis/status/585540107089928195

**Comment by marcobiedermann** [comment]
Okay, I see. Will come back to this in the few days.

**Comment by marcobiedermann** [comment]
Still not working for me. Should we close this one?

**Comment by stefanjudis** [comment]
yeah let's close it.

Marco Biedermann <notifications@github.com> schrieb am Mo., 20. Apr. 2015
um 22:30 Uhr:
