### ISSUE TITLE
Change created by

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#567]
Hey "Team" :P 

What about extending the "Brought to you by Stefan and Marco" and replace it by "Perf-tooling team" and some nice looking pictures on `/home`.

I'd be totally up for that.

@marcobiedermann @marhigh @radibit

**Comment by radibit** [comment]
Yeah, it will be really cool :sunglasses:

**Comment by stefanjudis** [comment]
@marcobiedermann ?

agree? and if so - wanna design s.th. or should I "design" with programmer eye. :P

**Comment by marcobiedermann** [comment]
Yup, +1 for this one. For now, I would only change the names and change the design later on. Or do you have something fancy in mind?

**Comment by stefanjudis** [comment]
sure something fancy. :)
