### ISSUE TITLE
Allign "read more" buttons on home

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#568]
@marcobiedermann 

Hey I think we should align the `read more` buttons that just went live.

How would you approach it?
`min-height` or `table-cell` and absolute positioning for the links?

Or would you go another way?

@marhigh

**Comment by marcobiedermann** [comment]
I would go with flex-box. I am currently playing around with this. Seams a lot of fun and would solve some complex issues. Support is IE10+ so I would go for it.

**Comment by stefanjudis** [comment]
Yeah - sounds good. 

Wanna fix it @marghigh?
