### ISSUE TITLE
vector

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#574]
https://github.com/Netflix/vector

**Comment by radibit** [comment]
Nice idea, but unfortunately the app is still not stable. At least on my end it's constantly dropping connection and there are still a lot of bugs as the creators stated!

**Comment by stefanjudis** [comment]
@radibit I'd go for it. Hey it's netflix. They'll become stable soon.

**Comment by radibit** [comment]
@stefanjudis agree on that :smiley:

**Comment by marcobiedermann** [comment]
added in c736bcc5b5cb1355777b90448fd3f6d31e9a2ae5
