### ISSUE TITLE
php respimg

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#576]
https://github.com/nwtn/php-respimg/

maybe @nwtn wanna add it himself when it's ready? :bowtie:

**Comment by nwtn** [comment]
I'd love to have it up; ditto the more-complete [grunt-respimg](https://github.com/nwtn/grunt-respimg/). I'll try to submit a PR in a few days if you like, but I'm also totally OK with you adding it/them directly.

**Comment by stefanjudis** [comment]
We'd love people to contribute - so if you can make it that'd be great! :bowtie:

**Comment by marcobiedermann** [comment]
@nwtn Are you still interested in submitting the tool by your own, or should we add it for you?

**Comment by nwtn** [comment]
unfortunately i have no capacity to do this (as my year-long absence attests to), so definitely feel free to add it.

**Comment by marcobiedermann** [comment]
@nwtn Thanks for your quick reply. I've just submitted a pull request by my own. See #1048
