### ISSUE TITLE
Put preview information into the slides section

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#577]

**Comment by stefanjudis** [comment]
![screenshot 2015-04-09 21 29 24](https://cloud.githubusercontent.com/assets/962099/7075069/8610f40a-deff-11e4-9954-1f46191d2076.png)

**Comment by stefanjudis** [comment]
@marcobiedermann 

Hey mister,

this one needs a couple of CSS adjustments.
Wanna jump in or shall I enter you holy area. :)

**Comment by marcobiedermann** [comment]
![perf-tooling-slides](https://cloud.githubusercontent.com/assets/5244986/7077790/13e6e938-df14-11e4-9583-ee4887f682e0.png)

Better?

**Comment by stefanjudis** [comment]
Nice!!!

Yeah fine for me! I'll create PR. you'll merge? :P
