### ISSUE TITLE
Register sitemap.xml at webmastertools

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#590]
https://github.com/stefanjudis/perf-tooling/pull/474

**Comment by stefanjudis** [comment]
![screenshot 2015-04-18 14 02 07](https://cloud.githubusercontent.com/assets/962099/7215339/8a176c48-e5d3-11e4-8729-3f94a567f743.png)

**Comment by marcobiedermann** [comment]
Nice, hopefully books will be listed in the search results as well

![perf-tooling-google](https://cloud.githubusercontent.com/assets/5244986/7215432/adca2eec-e5d7-11e4-9299-79563c5ecad7.png)
