### ISSUE TITLE
Request for addition of new book. 

### ISSUE THREAD

**Issue by vigneshshanmugam** [stefanjudis/perf-tooling#603]
Include http://www.bookofspeed.com/ by Stoyan Stefanov unde books section. 

Will do a PR if you want :).

**Comment by marcobiedermann** [comment]
@vigneshshanmugam Sure, go for it. PR are always very welcome. You will be listed as a contributor on the front page after deploy

**Comment by vigneshshanmugam** [comment]
Cool. Done with the PR  https://github.com/stefanjudis/perf-tooling/pull/614

**Comment by vigneshshanmugam** [comment]
PR got merged. Closing the issue.

**Comment by stefanjudis** [comment]
:+1:
