### ISSUE TITLE
external svg sprite

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#608]
I would like to make some test with our icons.
Currently we inline `icons.svg` into every page and reference it via `<use>` tag.
According to [this article](https://css-tricks.com/svg-use-external-source/) you can link an external file and use the `#` (hash) for each icon. The benefit of this technique would be that we serve less bytes and the file can be cached.

@stefanjudis When I reference the icon, I get `Cannot GET /public/icons.svg`.
How do I set it up properly?

I changed the template from:
```
<div class="svgIcons"><%= svg %></div>

…

<svg>
  <use xlink:href="#icon-twitter" />
</svg>
```
to:

```
<svg>
  <use xlink:href="public/icons.svg#icon-twitter" />
</svg>
```

**Comment by stefanjudis** [comment]
Give `GET /icons.svg` a try. :)
