### ISSUE TITLE
font-performance collection

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#611]
check:

http://deanhume.github.io/typography/font-performance.html

**Comment by marcobiedermann** [comment]
* [Font Loading Techniques](http://davidwalsh.name/font-loading): :-1: because this just references other articles
* [Fixing the 'Blank Text' Problem](https://www.igvita.com/2015/04/10/fixing-the-blank-text-problem/): :+1: 

The other articles are already covered

**Comment by marcobiedermann** [comment]
Fixing the 'Blank Text' Problem is added in #701.

@stefanjudis Can we close this issue?
