### ISSUE TITLE
redirect no-www to www

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#613]
`http://perf-tooling.today/` should be redirected to `http://www.perf-tooling.today/`.
You also have to verify both sites in Google Webmaster Tools and add the redirect there. Otherwise this is duplicated content for search engines

**Comment by stefanjudis** [comment]
> You also have to verify both sites in Google Webmaster Tools and add the redirect there.

They are both verfied.

Adding redirect on webmastertools? That doesn't make sense. :)

**Comment by marcobiedermann** [comment]
You can set a preferred URL in Google Webmaster Tools.
Redirect the site either with a `htaccess` or at your domain hoster.
`canonical` would is just for search engines. Not for actual redirects

**Comment by stefanjudis** [comment]
> canonical would is just for search engines. Not for actual redirects

I know - that's why I'm asking about setting to `canonical` for one of the two versions. To avoid the redirect.

Personally I hate this redirect for SEO purposes sh... and would like to avoid it.

Current settings:

![bildschirmfoto 2015-04-13 um 16 15 46](https://cloud.githubusercontent.com/assets/962099/7117376/7ea5ed6e-e1f8-11e4-9256-73cc0c8e96e2.png)

**Comment by marcobiedermann** [comment]
Alright, we add the meta tag

**Comment by stefanjudis** [comment]
Well this was asking?

If it's not working the same way as the redirect, we can implement the redirect. But I try to avoid SEO topics as much as I can, so you might be the expert. :)

**Comment by marcobiedermann** [comment]
From a SEO point the both are pretty much the same.
I prefer to choose one of the both and redirect the other one.
I've read that a url with `www` has a slightly better UX.

Pros:
* Save `canonical ` meta tag
* Only one domain if copy & pasted and posted on other sites
* Less work in the future if we add more sites

Cons:
* Redirect slows a bit down

**Comment by stefanjudis** [comment]
> Save canonical meta tag

I'd prefer this 50bytes rather than taking the time for redirection.

> Only one domain if copy & pasted and posted on other sites

People treat `www` as not mendatory. if both works it's kind of the same isn't it?

> Less work in the future if we add more sites

I don't get this one.

As said - if you wanna have it you can have it. But I was never convinced by this redirect. :blush: thing.

**Comment by stefanjudis** [comment]
Done. :)
