### ISSUE TITLE
Icon some icons changed size?

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#629]
Just deployed latest release and some icons look weird ( the magnifier & video icons )?

@marcobiedermann 

Wanna check? Intended?

**Comment by marcobiedermann** [comment]
Yeah, you are right. But the icons are NOW in the right size. I removed any spacing from the icons, so they are much smaller in file size. The problem we have now is that all icons have a size of 2rems. I am aware of this and will fix it as soon as I have the time for it :)
