### ISSUE TITLE
Openening additional communcation channel

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#631]
Hey Folks,

I'm just playing with the idea of opening an additional channel.

Current communication from my side:

- @marcobiedermann : Github & Twitter
- @radibit : personally, skype, slack, Github
- @marhigh : personally, skype, Github

I've got the feeling that, Github sometimes brings delays with it, becaus there are just too many mails send ( I've got github mails disabled also ;) ).

Would you be up for a slack organization. I've got quite good experience with it and the github implementation is great there.

What do you think?

Using s.th. like this, would give me also the benefit of informing you, when I'm releasing stuff and working on the newsletter. :)

**Comment by radibit** [comment]
@stefanjudis @marcobiedermann @marhigh 

I've just started using slack about two months ago and it's working really great for me! 
So I personally think your idea for dedicated slack channel is really good :smiley:

**Comment by stefanjudis** [comment]
@marcobiedermann @marhigh @radibit 

Everybody except @radibit received an invitation.
Let's give it a shot. :)

**Comment by marcobiedermann** [comment]
Joined! Yeah let's give it a try

**Comment by stefanjudis** [comment]
Woooohooooo! :)
