### ISSUE TITLE
More Weight Doesn't Mean More Wait

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#647]
[http://www.filamentgroup.com/lab/weight-wait.html](http://www.filamentgroup.com/lab/weight-wait.html)

**Comment by marcobiedermann** [comment]
We already cover that #637

**Comment by radibit** [comment]
@marcobiedermann Sorry about that, my mistake.

**Comment by stefanjudis** [comment]
no prob. :)
