### ISSUE TITLE
Sprint.js

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#658]
https://github.com/bendc/sprint

Hmm… I am not sure about this one. It is not a performance specific tool. It just uses some new API techniques.

**Comment by stefanjudis** [comment]
hmm... I don't sure about that... Then e.g. we would have to include shoestring also.

And actual recommendation atm is more like "use native dom methods" when possible regarding browser support.

Spring.js is really just wrapping dom methods with some sugar. No surprise about that it's faster. :D 

@radibit @marhigh

**Comment by radibit** [comment]
I agree with what @stefanjudis clarified, though the library looks interesting I think we can skip it.

**Comment by stefanjudis** [comment]
@marcobiedermann 

So I'll close it. Feel free to reopen as always. :)
