### ISSUE TITLE
Public Slack Chat

### ISSUE THREAD

**Issue by marhigh** [stefanjudis/perf-tooling#671]
I would like to propose that we create a public Slack channel for Perf-Tooling. The link could be sent out in our newsletters and that way our community could chat more with each other and help each other out.

**Comment by stefanjudis** [comment]
:+1: 

Also putting it on home might be great.

**Comment by radibit** [comment]
@marhigh 

I think it is a great idea :smiley: , also I agree with @stefanjudis to place it on the home page!

**Comment by marcobiedermann** [comment]
I know lots or repos use [Gitter](https://gitter.im/) for public chats. But I have not tried it yet.
Sure, we can add it to the home page, sounds good.

**Comment by gokulkrishh** [comment]
Using Gitter is good idea.

**Comment by stefanjudis** [comment]
It's gitter so we can close here. :)
