### ISSUE TITLE
pagespeedThis

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#677]
https://github.com/kimblim/pagespeedThis

maybe @kimblim wanna propose a PR? ;)

**Comment by kimblim** [comment]
I have no idea what you just asked me to do ;) I know what PR means, but where should I do it and how? (I don't normally use GitHub that much) :)

**Comment by stefanjudis** [comment]
Haha - sorry for that.

> Or propose a pull request and add a tool by adding a JSON file at data/articles, data/slides, data/tools or data/videos. The JSON files in these folders will be automatically rendered using a template based in templates/index.tpl

> We would like this project to become a shared resource maintained by the community, so if you have any ideas on how to improve it or make it better, please let us know and file an issue. :)

So the idea is, that we're building up a community driven resource about performance related resource. You'll find this at perf-tooling.today.

I think we'd add your project - but it would be even more great if you could add it yourself ( and maybe spread the word ). Adding the tool yourself will take ~2min ( forking, adding json file, propose PR ). ;)

If you're busy or don't like the project - no prob. :)
