### ISSUE TITLE
WebP Image format

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#678]
Serve WebP image format for supported browsers:
* add [gulp-webp](https://github.com/sindresorhus/gulp-webp) to generate webp format
* use `<picture>` element
* add webp format to book data

The json data could look like this:
```
"img" : {
  "src" : {
    "jpg": "book-of-speed.jpg",
    "webp": "book-of-speed.wep"
  }
  "width" : 200,
  "height" : 264
},
```

**Comment by stefanjudis** [comment]
I wouldn't duplicate the date in `src` and go with something like `path` and available `formats` or something.

But big :+1: from my side. :)

**Comment by stefanjudis** [comment]
@marcobiedermann let's please not set milestones for tickets. This probably won't make it in this release ( which included already 25 tickets ), or?
