### ISSUE TITLE
open-source-performance-dashboard

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#693]
http://www.peterhedenskog.com/blog/2015/04/open-source-performance-dashboard/ by @soulgalore

**Comment by marcobiedermann** [comment]
:+1: @soulgalore Nice article. Would you like to add it by yourself via PR?

**Comment by soulgalore** [comment]
@marcobiedermann thanks, yep can fix it tonight.

**Comment by stefanjudis** [comment]
Also done already. Thanks @soulgalore. :bowtie:
