### ISSUE TITLE
RAIL

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#707]
https://docs.google.com/presentation/d/13AJe2Ip4etqA8qylrva7bEgu1_hAvsq_VQiVOAxwdcI/present?slide=id.p19

**Comment by radibit** [comment]
I think we should add this resource :+1: 

Also I found a video of the same presentation as part of the Loop Conf - [link](https://www.youtube.com/watch?v=CceyqktMoRw) 

Which type do you think will be more valuable :-)

**Comment by stefanjudis** [comment]
@radibit We currently list both types for several talks - and I think that's fine to not limit visitors. :)

**Comment by radibit** [comment]
@stefanjudis Ok, than I will add the both of them. Thanks!
