### ISSUE TITLE
Perfschool

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#711]
https://github.com/bevacqua/perfschool

no idea how to add this. but this looks really really cool.

**Comment by marcobiedermann** [comment]
Maybe we could add a section called courses. There are also some Google and Udacity courses out there.

**Comment by radibit** [comment]
I think adding courses section is a good idea. Moreover in the future we can add video tutorials prepared by us, why not :smiley:

**Comment by stefanjudis** [comment]
> Moreover in the future we can add video tutorials prepared by us, why not :smiley:

:heart: it!!!
