### ISSUE TITLE
Stylesheet not fetched from the correct endpoint on initial load

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#712]

**Comment by radibit** [comment]
@stefanjudis 

The reason why the stylesheet is not requested from the CDN endpoint is because of the logic behind reading the css file and inline its content in the template:

```json
css : fs.readFileSync( './public/main-' + revisions.styles + '.css', 'utf8' ),
```

Can you please suggest a proper way how to actually read the file provided from the CDN so I can inline its content when the cookie is not available ( the initial load )?

**Comment by stefanjudis** [comment]
This is fixed. :tada:
