### ISSUE TITLE
Mobile Image Processing

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#757]
https://www.youtube.com/watch?v=jP68rCjSSjM

:+1: Really good talk. I like it.

**Comment by stefanjudis** [comment]
Ja I saw that one also - but was not sure. :)

**Comment by marcobiedermann** [comment]
@radibit Do you have any opinion on this one whether to include this or not?

**Comment by radibit** [comment]
@marcobiedermann Yeah, saw it already and I think it's quite interesting, so :+1: :smiley:

**Comment by stefanjudis** [comment]
Well then. :)
