### ISSUE TITLE
Add Travis and build process

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#78]
https://david-dm.org/ for dep checks

And CSSLint, JSHint and check for valid *.json files. :)

https://www.npmjs.org/package/gulp-jsonlint

**Comment by marcobiedermann** [comment]
@stefanjudis Could you just hit this little "[Sign In](https://travis-ci.org/)" button so we can integrate travis?! This will help us to spot bugs more easily :)

**Comment by stefanjudis** [comment]
@marcobiedermann registered this repo at travis. Simply adding the `travis.yml` should do it. :)
