### ISSUE TITLE
How Fast Is Fast Enough (for a Web Page to Load)?

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#785]
[http://www.soasta.com/blog/website-monitoring-fast-enough-user-experience/](http://www.soasta.com/blog/website-monitoring-fast-enough-user-experience/)

**Comment by stefanjudis** [comment]
@radibit Can you PR?

I'm a bit busy atm. :blush:

**Comment by radibit** [comment]
@stefanjudis absolutely! :)
