### ISSUE TITLE
demo tool

### ISSUE THREAD

**Issue by marcobiedermann** [stefanjudis/perf-tooling#787]
How about adding a demo tool which shows all platforms if `?debug=true` is set?

**Comment by stefanjudis** [comment]
No prob. :+1: 

Can't promise when I got time for this.

**Comment by radibit** [comment]
I will try to do it this weekend.

@marcobiedermann one question - currently in debug mode we're displaying the data source (JSON) behind the selected category, so the idea about the tools is to have a demo entry with all available platforms and by platforms we're referring to `broccoli, module, python, gulp etc.`, right?

**Comment by marcobiedermann** [comment]
Exactly. This way it is easier to get a few of all possible platforms

**Comment by radibit** [comment]
@marcobiedermann Can you please checkout [feature/787-demo-tool](https://github.com/stefanjudis/perf-tooling/tree/feature/787-demo-tool) and verify if this is what you expect from the demo tool entry in debug mode :-)

**Comment by stefanjudis** [comment]
@radibit 

I think if doing this it would make sense to also give a max number of tags and fill the stars with high star counts.

What do you think?

**Comment by radibit** [comment]
@stefanjudis 

Sure, I will add these properties as well.

**Comment by stefanjudis** [comment]
Maybe wanna place it here?

https://github.com/stefanjudis/perf-tooling/blob/master/app.js#L483-L518

**Comment by marcobiedermann** [comment]
@radibit Nice work. Just one thing. The tags should be an array. Otherwise they will be repeated for every platform.

![demo-tool](https://cloud.githubusercontent.com/assets/5244986/8580022/7be0ccbc-25b8-11e5-886a-70a93ce7f8eb.png)

**Comment by stefanjudis** [comment]
Uuuuh haven't seen it so far.

The icons all togther are super nice!!! :+1:

**Comment by radibit** [comment]
@marcobiedermann Yes, about the tags, it was intentionally in order to fill in a big number of them, but I guess it doesn't make sense :smiley: 

Thanks guys! I will create a pull request then.
