### ISSUE TITLE
Fancier approach to navigation

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#79]
@marcobiedermann 

I'd like to play around with putting the mobile navigation to the bottom, because it's much better reachable for the thumb. What do you think of that?

https://medium.com/@moreiraDesigns/rethinking-the-mobile-navigation-947096a07dee

**Comment by marcobiedermann** [comment]
I've seen an other article about this. Yeah there is a point but I think people are more familiar with a navigation on top of the page. I would close this issue, if you are ok?

**Comment by stefanjudis** [comment]
Sure. :)
