### ISSUE TITLE
Performance beyond page load

### ISSUE THREAD

**Issue by ApoorvSaxena** [stefanjudis/perf-tooling#811]
[http://www.slideshare.net/ApoorvSaxena/performance-beyond-page-load-jquery-conference](http://www.slideshare.net/ApoorvSaxena/performance-beyond-page-load-jquery-conference)

Slides for the talk "Performance beyond page load" presented at jQuery Conference 2015.

**Comment by sotayamashita** [comment]
@ApoorvSaxena Is this link broken ?

**Comment by marcobiedermann** [comment]
@sotayamashita @ApoorvSaxena Just fixed the link :) Thanks for the issue. Will have to take a look at the slides later on. If one of you like to create a pull request, feel free to do so

**Comment by ApoorvSaxena** [comment]
Here's the pull request: https://github.com/stefanjudis/perf-tooling/pull/812

**Comment by marcobiedermann** [comment]
fixed in #812
