### ISSUE TITLE
Performance audit for Materialup.com

### ISSUE THREAD

**Issue by ApoorvSaxena** [stefanjudis/perf-tooling#816]
http://perfaudit.com/case-study/materialup.com/

**Comment by stefanjudis** [comment]
:+1: 

@ApoorvSaxena Wanna provide a PR? That would be great. :)

**Comment by ApoorvSaxena** [comment]
Thanks Stefan, have opened one: https://github.com/stefanjudis/perf-tooling/pull/818

**Comment by stefanjudis** [comment]
Nice... I just merged it. 

Thanks for your contribution... We're kind of busy currently, so any help is more than welcome. :bowtie:
