### ISSUE TITLE
Measuring frontend performance, the missing ingredient

### ISSUE THREAD

**Issue by panrafal** [stefanjudis/perf-tooling#830]
https://lab.getbase.com/measuring-frontend-performance-the-missing-ingredient/

**Comment by stefanjudis** [comment]
hey @panrafal, 
sorry for the delay... It was summer time and I was on vacation.

I'd like to add the article to perf-tooling. What about adding it yourself - as we prefer to expand the list of contributors? :blush: 

If not no problem. :)
I can add it also. :)

**Comment by panrafal** [comment]
Hello @stefanjudis ! 
It would be great if you could add it this time around :) Thanks!

**Comment by stefanjudis** [comment]
No prob. :)
