### ISSUE TITLE
Perf-Planet books

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#839]
check https://www.pinterest.com/perfplanet/wpo-books/

**Comment by radibit** [comment]
I checked the pinned items and the list below represents what it is not listed on perf-tooling at the moment:
- [Time is money](http://shop.oreilly.com/product/0636920041450.do)
- [Implementing responsive design](http://www.implementingresponsivedesign.com/)
- [High performance single page applications](http://www.amazon.com/High-Performance-Single-Page-Applications-ebook/dp/B00HUW2HLQ)
- [Website Optimization](http://shop.oreilly.com/product/9780596515089.do)
- [Complete Web Monitoring](http://shop.oreilly.com/product/9780596155148.do) 

I excluded two of the books as they are not directly connected to the performance topic - [JavaScript Patterns](http://shop.oreilly.com/product/9780596806767.do) and [Closure: The definitive guide](http://shop.oreilly.com/product/0636920001416.do)

**Comment by stefanjudis** [comment]
@radibit A PR for these would be awesome!!! :tada:

**Comment by radibit** [comment]
Of course I will do it later today :smiley:
