### ISSUE TITLE
Implement a seperated audit section

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/perf-tooling#872]
Heyoooo!

This trend of audits is still going on.
What do you think of adding a new category for that and list them there all together.
We already include a hand full in articles and videos - it might be a good idea to group them, as they're a special case of reasource?

What do you think?

@radibit @marcobiedermann @marhigh 

Additional audits found:

- https://docs.google.com/document/d/1K-mKOqiUiSjgZTEscBLjtjd6E67oiK8H2ztOiq5tigk/edit?pli=1#heading=h.vwra8t2fwx8t
- https://docs.google.com/document/d/1tsOXooeJhSwGmCRGisr98o1KBhqTvO9i49X_OSn7LXc/edit
- https://docs.google.com/document/d/1yJoMEdFME04maB_hlGhARTeys-DdeHRqU7zn-z4CFcA/edit#heading=h.v23t53p6nkzl
- https://github.com/reddit/reddit-mobile/issues/247
- https://docs.google.com/document/d/1Xv3qNROxPOOtau7V3UbHHJyA-5AmGC4s-hZKBe0Lx6U/edit#heading=h.zd1epp21myou
- https://docs.google.com/document/d/1-Kdmub-7WfA45gSyG2GYQOyEkkjmG1gKq0zJwhrWbPA/edit
- https://docs.google.com/document/d/15VSNoBP3OK64l5Jc_w63sgW88RUn3ve2qV7Jrrfc5A8/edit#heading=h.v23t53p6nkzl

**Comment by radibit** [comment]
@stefanjudis 

Great idea :raised_hands: 

I think this perf audits trend is really good, helpful and last but not least enjoyable to read or watch those type of resources :smiley:
