### ISSUE TITLE
Performance budget builder

### ISSUE THREAD

**Issue by radibit** [stefanjudis/perf-tooling#990]
[http://bradfrost.com/blog/post/performance-budget-builder/](http://bradfrost.com/blog/post/performance-budget-builder/)

**Comment by stefanjudis** [comment]
Well... I saw this one... And I don't think it has much benefit you're up for it?

**Comment by radibit** [comment]
Yeah, totally fine - just wanted to get other opinion/s if it will be a valuable resource :)
