### ISSUE TITLE
Tool proposal: CoScale

### ISSUE THREAD

**Issue by parijs** [stefanjudis/perf-tooling#998]
It would be nice if you could add CoScale, a [full stack web performance monitoring tool](www.coscale.com) to the tools section.

URL: www.coscale.com

Short description: SaaS-based monitoring of server metrics, page load times, and custom metrics and events. Use of anomaly detection to detect performance issues.

Some tags or relevance could be: metrics, monitor, analyze, performance, timings, server, webserver, database, caching

You can find our github extensions here: https://github.com/CoScale

**Comment by stefanjudis** [comment]
Sure.. Pr would be great. ;)
